### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by derpferd** [UMDLARS/space_invaders#5]
Using this bot:
```
func is_barrier(s) {

    if s is BARRIER_4 or s is BARRIER_3 or s is BARRIER_2 or s is BARRIER_1 {
        return s
    } else {
        return 0
    }

}

func is_invader(s) {

    if s is INVADER_0 or s is INVADER_2 or s is INVADER_1 {
        return s
    } else {
        return 0
    }

}

move = stay

if is_barrier(player_center) or is_invader(player_center) or is_invader(player_left) or is_invader(player_left_minus_one) or is_invader(player_right_plus_one) or player_center is MISSILE {
    move = fire
}

if not is_barrier(player_left_minus_one) {
    move = east
}

if not is_barrier(player_right_plus_one) {
    move = west
}
```

Got this error once every ~30 games.

```
Traceback (most recent call last):
  File "/home/umdcyl/.local/share/virtualenvs/space-QLoIfC5d/lib/python3.6/site-packages/CYLGame/Server.py", line 204, in sim_avg
    score = runner.run_for_avg_score(room, times=self.avg_game_count, func=self._avg_game_func)
  File "/home/umdcyl/.local/share/virtualenvs/space-QLoIfC5d/lib/python3.6/site-packages/CYLGame/Game.py", line 332, in run_for_avg_score
    scores += [self.run(room.rand_seeded).score]
  File "/home/umdcyl/.local/share/virtualenvs/space-QLoIfC5d/lib/python3.6/site-packages/CYLGame/Game.py", line 310, in run
    game.do_turn()
  File "game.py", line 419, in do_turn
    self.handle_key(self.player.move)
  File "game.py", line 466, in handle_key
    self.move_invaders()
  File "game.py", line 292, in move_invaders
    if positions[0][0] - 1 < 0:
IndexError: list index out of range```

**Comment by derpferd** [comment]
This was discovered by @pahp
